ersion: '3.8'

services:
  web:
    build: .
    container_name: mediaclass_app
    command: uvicorn main:app --host 0.0.0.0 --port 80
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./quiz.db:/app/quiz.db
      - ./static/avatars:/app/static/avatars
